import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, padding: 20, alignItems: "center" },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
    marginTop: 30,
  },
  headerText: { color: "white", fontSize: 16, fontWeight: "bold" },
  progressContainer: { alignItems: "center", marginVertical: 10 },
  progressText: { color: "white", fontSize: 18, fontWeight: "bold" },
  progressBar: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#2E7D32",
    padding: 15,
    borderRadius: 15,
    width: "100%",
    justifyContent: "space-between",
    marginTop: 10,
  },
  progressCircleActive: {
    width: 35,
    height: 35,
    borderRadius: 17.5,
    borderWidth: 1,
    backgroundColor: "white",
    alignItems: "center",
    justifyContent: "center",
    borderColor: "#FFC107",
  },
  innerCircle: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: "#FFC107",
  },
  progressCircle: {
    width: 35,
    height: 35,
    borderRadius: 30,

    justifyContent: "center",
    alignItems: "center",
    borderColor: "#fff",
    borderWidth: 1.5,
  },
  progressCircleBoder: {
    width: 40,
    height: 40,
    borderRadius: 30,
    backgroundColor: "transform",
    justifyContent: "center",
    alignItems: "center",
    borderColor: "#FFC107",
    borderWidth: 1.5,
  },
  activeStep: {
    backgroundColor: "#FFC107",
    borderColor: "white",
    borderWidth: 2,
  },
  activeStepText: { color: "white", fontWeight: "bold", textAlign: "center" },
  stepText: { color: "black", fontWeight: "bold" },
  dashedLine: {
    width: 8,
    height: 1,
    backgroundColor: "white",
    borderStyle: "dashed",
    justifyContent: "center",
    textAlign: "center",
    marginBottom: 17,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#FFC107",
    marginVertical: 5,
  },
  imageContainer: {
    position: "relative",
  },
  successBorder: {
    borderWidth: 4,
    borderColor: "#73A442",
    borderRadius: 15,
  },
  errorBorder: {
    borderWidth: 4,
    borderColor: "#C6463A",
    borderRadius: 15,
  },
  iconError: {
    position: "absolute",
    top: -15,
    right: -15,
    backgroundColor: "#C6463A", // Nền màu xanh hoặc đỏ
    width: 42,
    height: 42,
    borderRadius: 30, // Tạo vòng tròn
    alignItems: "center",
    justifyContent: "center",
  },
  image: { width: 370, height: 317, borderRadius: 10 },
  stepSuccess: {
    backgroundColor: "#73A442", // Nền màu xanh hoặc đỏ
    width: 35,
    height: 35,
    borderRadius: 30, // Tạo vòng tròn
    alignItems: "center",
    justifyContent: "center",
    borderColor: "#fff",
    borderWidth: 1,
  },
  stepFailure: {
    backgroundColor: "#C6463A", // Nền màu xanh hoặc đỏ
    width: 35,
    height: 35,
    borderRadius: 30, // Tạo vòng tròn
    alignItems: "center",
    justifyContent: "center",
    borderColor: "#fff",
    borderWidth: 1,
  },
  iconSuccess: {
    position: "absolute",
    top: -15,
    right: -15,
    backgroundColor: "#73A442", // Nền màu xanh hoặc đỏ
    width: 42,
    height: 42,
    borderRadius: 30, // Tạo vòng tròn
    alignItems: "center",
    justifyContent: "center",
  },
  instruction: {
    fontSize: 16,
    color: "white",
    textAlign: "center",
    marginVertical: 10,
  },
  buttonContainer: {
    flexDirection: "row",
    justifyContent: "space-around",
    width: "80%",
    marginTop: 5,
    marginBottom: 10,
  },
  buttonSuccess: {
    width: 90,
    height: 90,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#71A162",
    borderRadius: 10,
  },
  buttonFail: {
    width: 90,
    height: 90,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#71A162",
    borderRadius: 10,
  },
  buttonTextSuccess: { color: "white", fontSize: 12, marginTop: 5 },
  buttonTextFail: { color: "white", fontSize: 12, marginTop: 5 },
  confirmButton: {
    padding: 12,
    borderRadius: 25,
    width: 160,
    alignItems: "center",
    paddingBottom: 8,
    height: 46,
  },
  confirmText: { color: "white", fontSize: 18, fontWeight: "bold" },
  note: { fontSize: 12, color: "white", textAlign: "center", marginTop: 10 },
  modalContent: {
    backgroundColor: "white",
    padding: 10,
    borderRadius: 10,
    alignItems: "center",
  },
  modalTitle: {
    fontSize: 24,
    fontWeight: "700",
    color: "#478449",
  },
  modalMessage: {
    fontSize: 14,
    textAlign: "center",
    marginBottom: 10,
    fontFamily: "SVN-Gotham",
  },
  modalButtons: {
    flexDirection: "row",
    justifyContent: "space-around",
    width: "100%",
  },
  cancelButton: {
    width: 150,
    borderWidth: 1,
    borderColor: "#B70002",
    borderRadius: 20,
    paddingVertical: 8,
    paddingHorizontal: 20,
  },
  cancelText: {
    textAlign: "center",
    color: "#B70002",
    fontWeight: "bold",
    fontSize: 16,
  },
  continueButton: {
    width: 150,
    backgroundColor: "#B70002",
    borderRadius: 20,
    paddingVertical: 8,
    paddingHorizontal: 20,
  },
  continueText: {
    color: "white",
    textAlign: "center",
    fontWeight: "bold",
    fontSize: 16,
  },
});
